name = "prunt_dev_board_1"
description = "Prunt development board 1."
version = "0.1.0-dev"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]

executables = ["prunt_dev_board_1"]

[[depends-on]]
prunt_physical_types = "*"
prunt_glue = "*"
[[pins]]
prunt_physical_types = { path = "../prunt_physical_types" }
prunt_glue = { path = "../prunt_glue" }

[build-switches]
release.optimization = []
