name = "prunt_dev_board_1"
description = "Prunt development board 1."
version = "0.1.0-dev"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]

executables = ["prunt_dev_board_1"]

[[depends-on]]
prunt_physical_types = "*"
prunt_motion_planner = "*"
prunt_gcode_parser = "*"
prunt_stepgen = "*"
[[pins]]
prunt_physical_types = { path = "../prunt_physical_types" }
prunt_motion_planner = { path = "../prunt_motion_planner" }
prunt_gcode_parser = { path = "../prunt_gcode_parser" }
prunt_stepgen = { path = "../prunt_stepgen" }

[build-switches]
release.optimization = [
  "-O3",
  "-gnatn",
  "-fdata-sections",
  "-ffunction-sections",
  "-flto=auto",
  "-fuse-linker-plugin",
  "-fno-pie",
  "-fno-pic",
  "-ffat-lto-objects"
]
